name: 'Build Dev Container' 
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  # Push images to GHCR.
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Image built from .devcontainer/devcontainer.json, with all the required dependencies to compile and run Serenity
      - name: Build Base Dev Container Image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/serenity:base
          push: always

      # The image above with a pre-compiled build of Serenity
      - name: Build Dev Container Image with Project Pre-Compiled 
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/serenity:compiled
          cacheFrom: ghcr.io/${{ github.repository_owner }}/serenity:base
          push: always
          # Compile serenity
          runCmd: Meta/serenity.sh build